name: Academia Atenea
favicon: null
layout_spectrum: 0.3796662832610309
typography_spectrum: 0.31969336536712945
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.05907944333739579
  lightness: 0.06186285009607673
  saturation: 0.3363866659346968
  rhythmicContrast: 0.948509774170816
purpose: []
